server:
  host: "localhost"
  port: 8814
  logging:
    level: "debug"

jwt:
  ttl: 2678400
  secret_key: "suppersecretkey"

database:
  sql:
#    host: "usof-mysql"
#    port: 3306
    host: "localhost"
    port: 5678
    user: "usof"
    name: "usof"
    password: "password"

aws:
  region: "eu-north-1"
#  access_key_id: "SECCRETACCESSKEYID"
#  secret_access_key: "SECCRETACCESSKEY"
  bucket_name: "usof-s3"
  public_base: "https://usof-s3.s3.eu-north-1.amazonaws.com"