server:
  host: "localhost"
  port: 8814
  logging:
    level: "debug"

jwt:
  ttl: 2678400
  secret_key: "suppersecretkey"

database:
  sql:
#    host: "localhost"
#    port: 5678
    host: "usof-mysql"
    port: 3306
    user: "usof"
    name: "usof"
    password: "password"
